---
title: "Overview"
---

Over the course of this 1-day training class you will learn how to run water use scenarios with the
Wood River Valley (WRV) groundwater-flow model.

## Tentative Schedule

* **8:00--9:15** Welocme and introductions (Jim Bartoling, USGS)

* **8:15--9:15** Overview of WRV groundwater-flow-model publication, archive, and repository (Jason Fisher, USGS)

* **9:15--9:35** Break

* **9:30--10:30** Introduction to the [R-programming](r-prog.html) language (Jason Fisher, USGS)

* **10:45--11:45** Running and analysing the [calibrated model](calib-model.html) (Jason Fisher, USGS)

* **11:45--12:45** Lunch

* **12:45--1:30** Running and analysing the calibrated model (Jennifer Sukow, IDWR)

* **1:30--2:00** Running scenarios using the fully populated model, overview of example scenarios (Jennifer Sukow, IDWR)

* **2:00--2:15** Break

* **2:15--3:00** Scenerio 1: an example simulation of managed recharge (Jennifer Sukow, IDWR)

* **3:00--4:30** [Scenerio 2](scenario-2.html): an example simulation of idling irrigated lands (Jason Fisher, USGS)

## Software

Something






## workflow

1. A "baseline" simulation is generated by running the WRV model with the historic
   water budget from model calibration (we've already completed this step)

2. Stresses are added to the historic water budget and the WRV model is
   run again with the revised MODFLOW Well file ("*.wel")

3. Results from the scenario simulation and the baseline simulation are differenced
   to find the predicted change in flux or head
